version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: marketplace-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: marketplace
      MYSQL_USER: marketplace
      MYSQL_PASSWORD: marketplace123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - marketplace-network
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marketplace-api
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/marketplace?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: marketplace
      SPRING_DATASOURCE_PASSWORD: marketplace123
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - marketplace-network
    volumes:
      - ./backend:/app
    working_dir: /app

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marketplace-web
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - marketplace-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

volumes:
  mysql_data:

networks:
  marketplace-network:
    driver: bridge
